dist: bionic
os:
  - linux
services:
  - docker
  - xvfb
language: node_js
node_js:
  - "11.0.0"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
# Install Chrome
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - dpkg
      - google-chrome-stable
before_install:
  - npm i -g @angular-devkit/schematics-cli @angular/cli @vue/cli ionic codecov
install:
  - npm ci
script:
  - npm run build
  - npm test && npm run coverage
  # create apps and confirm tests still pass
  - ./test-all.sh
after_success:
  - codecov
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
